@MutableDataService_HostAddress = https://localhost:65533/
@person = people/

### Create Person
# @name postPersonCreate
PUT {{MutableDataService_HostAddress}}{{person}}create
Content-Type: application/json

{
    "FirstName": "Lustig",
    "LastName": "Petra",
    "TelephoneConnections":
    [
        {
            "PhoneNumber": "12121212112"
        }
    ]
}

### Update Person

@newId = {{postPersonCreate.response.body.id}}

PATCH {{MutableDataService_HostAddress}}{{person}}update
Content-Type: application/json

{
    "Id": "{{newId}}",
    "FirstName": "Lustige",
    "LastName": "Fee"
}

### Delete Person

DELETE {{MutableDataService_HostAddress}}{{person}}delete/{{newId}} HTTP/1.1

