@url = https://127.0.0.1:65535/people


GET {{url}}openapi/v1.json

###
GET {{url}}

###

GET {{url}}/getpersonbyid/1

###

GET {{url}}/getpersonbyid/0


### Create new person
# @name postCreate
PUT {{url}}/createperson
Content-Type: application/json

{
    "FirstName" : "Test",
    "LastName": "User",
    "BirthDate": "1970-01-01"
}

###

@id = {{postCreate.response.body.id}}

### Update new person
PATCH {{url}}/updateperson
Content-Type: application/json

{
    "Id": "{{id}}",
    "FirstName" : "Test",
    "LastName": "User",
    "BirthDate": "2070-01-01",
    "TelephoneConnections": [
        {
            "Id": 3,
            "PhoneNumber": "420420"
        }
    ]
}

### Delete newly created person
DELETE {{url}}/deleteperson/{{id}} HTTP/1.1
